export const postsData = [
  {
    id: 1,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    thumbnail_url: 'Postexample.svg',
    author: '꾸러기',
    scrapCount: 102,
    scrap: false,
  },
  {
    id: 2,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    thumbnail_url: 'Postexample.svg',
    author: '뇽뇽맘',
    scrapCount: 12,
    scrap: false,
  },
  {
    id: 3,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    thumbnail_url: 'Postexample.svg',
    author: '원채영',
    scrapCount: 500,
    scrap: false,
  },
  {
    id: 4,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    thumbnail_url: 'Postexample.svg',
    author: '엄경호',
    scrapCount: 1,
    scrap: false,
  },
  {
    id: 5,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    thumbnail_url: 'Postexample.svg',
    author: '김철흥',
    scrapCount: 2,
    scrap: false,
  },
  {
    id: 6,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    thumbnail_url: 'Postexample.svg',
    author: '마루누나',
    scrapCount: 199,
    scrap: false,
  },
];
