export const postsData = [
  {
    id: 1,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    image: 'Postexample.svg',
    profileName: '꾸러기',
    bookmarks: 102,
    isFilled: false,
  },
  {
    id: 2,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    image: 'Postexample.svg',
    profileName: '뇽뇽맘',
    bookmarks: 12,
    isFilled: false,
  },
  {
    id: 3,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    image: 'Postexample.svg',
    profileName: '원채영',
    bookmarks: 500,
    isFilled: false,
  },
  {
    id: 4,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    image: 'Postexample.svg',
    profileName: '엄경호',
    bookmarks: 1,
    isFilled: false,
  },
  {
    id: 5,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    image: 'Postexample.svg',
    profileName: '김철흥',
    bookmarks: 2,
    isFilled: false,
  },
  {
    id: 6,
    title: '찜기 없이, 젓가락 하나로 만두 굽는 법',
    image: 'Postexample.svg',
    profileName: '마루누나',
    bookmarks: 199,
    isFilled: false,
  },
];
